### PR TITLE
Package updates

### LINKED ISSUE #501: Deprecation warnings with `Dart Sass 1.33.0`
`Dart Sass` [deprecated](https://sass-lang.com/documentation/breaking-changes/slash-div) the division syntax in version 1.33.0. `ember-resizable` [uses](https://github.com/evocount/ember-resizable/blob/v1.0.1/app/styles/ember-resizable.scss#L34) this syntax and there are warnings because of that in my console. It would be nice to fix those.

Not sure how to approach this though. `math.div` is not available in prior versions of `Dart Sass` so if `ember-resizable` wants to support older versions too, something else must be done. If I think of something, I'll post here.

### PR DESCRIPTION
**Pull request by boris-petrov**
I've ran `ember-cli-update`, updated all packages and fixed SASS deprecation warnings. Note that the last thing requires a *major* version of `ember-resizable` because it requires a specific `sass` version.

Fixes #501

P.S. cc @ttill

Unfortunately tests are not run on PRs. They pass locally on my side (but we'll see what `ember-try` says for all tested versions).

### CODE REVIEW

**Comment by ttill** [comment]
Thanks @boris-petrov for your effort! I currently do not have any capacities to spend on this addon. Given your repeated contributions, would you be interested in becoming a maintainer of this project? May I grant respective access to you?

**Comment by boris-petrov** [comment]
Hi, thanks for the idea! I will help as much as I can. How can we make it so that I can make new releases though? I’m not familiar with NPM’s release process.

**Comment by ttill** [comment]
I gave you maintainer access to this repo. After you issued a new release with `ember release` it is a mere `npm publish` to create and push a respective npm package. Do you have a npm account, which I can add to the project?

**Comment by boris-petrov** [comment]
Thanks, I accepted the access. I created an `npm` account - my username is `boris-petrov`. Is the process for releasing documented somewhere? Or is it generic for all Ember plugins?

**Comment by ttill** [comment]
Added your npm account to the repo. Release process is not documented. Sorry. I used [ember-cli-release-tag](https://github.com/mydea/ember-cli-release-tag), which is now deprecated. Documentation is available in historic versions of its readme. But maybe replacing it is simpler. I guess [release-it](https://github.com/release-it/release-it) has gained quite some popularity in the ember community. Before creating release tags by executing `ember release` (provided by ember-cli-release-tag) and creating the npm package with `npm publish` I always updated the changelog.

**Comment by boris-petrov** [comment]
Ah, yes, the changelog. Any guidelines for that? Did you use some automated tool? Thanks for answering all my questions! :)

**Comment by ttill** [comment]
I manually kept the changelog up to date while following the [Keep A Changelog guide](https://keepachangelog.com/en/1.0.0/).

**Comment by boris-petrov** [comment]
@ttill - I released v2.0.0. Please take a look at the CHANGELOG (and anything else you want to check) to see if all looks good to you.

Thank you again for the time and write access!

**Comment by boris-petrov** [comment]
I just don't understand why I asked `release-it` to publish to `npm` but it didn't do that... I had to manually `npm publish`. Very strange.

**Comment by ttill** [comment]
Awesome. Thank you so much! One more thing I previously forgot: You could also run `npm deploy:demo` (see package.json) to ensure the [demo](https://evocount.github.io/ember-resizable/) is up to date.

**Comment by boris-petrov** [comment]
Thanks for the tip. I added a [document](https://github.com/evocount/ember-resizable/blob/master/RELEASING.md) explaining the release process. If you see something missing from there, let me know. Thanks! :)

**Pull request merged**
